name: linkmesh_offline_chat
description: Flutter recreation of the supplied offline mesh chatting APK.
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  cryptography: ^2.7.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
